version: '3.9'
services:
  platform:
    command: 'bash -c "rm -f tmp/pids/server.pid && sleep 100d"'
    init: true
    build:
      context: ./platform
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./platform:/platform
    stdin_open: true
    tty: true
    env_file:
      - ./platform/.env.local
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    init: true
    image: "redis:7"
    command: "redis-server --requirepass redis"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
